# Site
repository: eyesho
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
wechat: eyesho
name: 徐飞
title: AI算法工程师
email: rootby@126.com
website: https://eyesho.github.io/
# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: frederickshyu
github_username:  eyesho
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: frederickshyu
#linkedin_username: jameswgrant
#xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: UClHck1qET0QL9m-0wWMFaeg
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: youtube
  icon: fab fa-youtube
  url: https://www.youtube.com/channel/UClHck1qET0QL9m-0wWMFaeg
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello，
  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/eyesho/rubot
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest things i ever created... 🤗 well,me and my friend.
        description: | # this will include new lines to allow paragraphs
          wating for update <mark>React</mark>
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: educloudcn group
        link: https://www.educloudcn.com/
        # link_text: boringcompany.com
        sub_title: ai engineer
        caption: April 2021 - Present
        quote: >
          Make education more accessible in remote area 
        description: | # this will include new lines to allow paragraphs
          waiting for update 
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 辽宁科技大学
        caption: 2016 - 2020
        sub_title: 电气工程及其自动化
        quote: >
          Established in 1948, 
        description: | # this will include new lines to allow paragraphs
        waiting for update 
        
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in writing code some of my other interests and hobbies are:
        - Swiming
        - Gaming
        - Table Tennis
        - Badminton
        - Orienteering
        - Basketball (primary level)
        - Sing :)
        - Reading (if that count)
        - yoga (have not started yet, planning on it )
        - Volleyball



      ![Trees](images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
